### ISSUE TITLE
plotROC

### ISSUE THREAD

**Issue by sachsmc** [ggplot2-exts/ggplot2-exts.github.io#11]
Is a ggplot2 extension even though the name doesn't begin with 'gg': [plotROC on github](http://github.com/sachsmc/plotROC) and [on CRAN](http://cran.r-project.org/package=plotROC)

**Comment by Emaasit** [comment]
That's no problem @sachsmc . The name does not have to begin with "gg"; as o\long as the package extends ggplot2 functionality. I have added it. Thanks.
