### ISSUE TITLE
ggspectra

### ISSUE THREAD

**Issue by aphalo** [ggplot2-exts/ggplot2-exts.github.io#12]
Hi.
My package 'ggspectra' was accepted today by CRAN. It does both extend 'ggplot2' and provide wrappers but depends on another two of my packages 'photobiology' and 'photobiologyWavebands'. I think it could be also listed...

[https://cran.rstudio.com/web/packages/ggspectra/](https://cran.rstudio.com/web/packages/ggspectra/)

[https://bitbucket.org/aphalo/ggspectra](https://bitbucket.org/aphalo/ggspectra)

[http://www.r4photobiology.info/](http://www.r4photobiology.info/)

Great idea to keep this list!

Thanks!

**Comment by Emaasit** [comment]
Thanks. I have added it to the develop branch. Will merge it to master in a few minutes.
