### ISSUE TITLE
Please add ggTimeSeries

### ISSUE THREAD

**Issue by dasather** [ggplot2-exts/ggplot2-exts.github.io#22]
https://github.com/Ather-Energy/ggTimeSeries
Thanks, and great work on putting together this platform for ggplot extenstions!

![calendar_heatmap-1](https://cloud.githubusercontent.com/assets/13588529/13064950/994b3124-d47d-11e5-91a8-4d9651bab99f.png)
![calendar_heatmap-2](https://cloud.githubusercontent.com/assets/13588529/13064951/994fd562-d47d-11e5-9dcb-17b7f5adea64.png)
![horizon-1](https://cloud.githubusercontent.com/assets/13588529/13064953/9959a74a-d47d-11e5-9b48-767337de7638.png)
![occurrence_dotplot-1](https://cloud.githubusercontent.com/assets/13588529/13064954/995d4026-d47d-11e5-94ba-bf24510a8ae7.png)
![steamgraph-1](https://cloud.githubusercontent.com/assets/13588529/13064955/995d6f10-d47d-11e5-8c53-794b1fe32ed3.png)
![waterfall-1](https://cloud.githubusercontent.com/assets/13588529/13064956/9984ba48-d47d-11e5-9b70-dae464fa5b01.png)

**Comment by shrektan** [comment]
wow, so cool
