### ISSUE TITLE
Please add ggthemr : Themes for ggplot2

### ISSUE THREAD

**Issue by bhaskarvk** [ggplot2-exts/ggplot2-exts.github.io#23]
Please add https://github.com/cttobin/ggthemr

**Comment by Emaasit** [comment]
@sainathadapa, @cttobin I am getting the following errors: 

> ggthemr('dust')
> Error: No geom called GeomJitter.
> In addition: Warning messages:
> 1: `axis.ticks.margin` is deprecated. Please set `margin` property  of `axis.text` instead 
> 2: New theme missing the following elements: panel.ontop, strip.switch.pad.grid, strip.switch.pad.wrap 
> 
> ggthemr:::preview_theme()
> Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
>   object 'preview_theme' not found

This is my session info:

> sessionInfo()
> R version 3.2.3 (2015-12-10)
> Platform: x86_64-pc-linux-gnu (64-bit)
> Running under: Ubuntu 14.04.3 LTS

**Comment by sainathadapa** [comment]
@cttobin didn't update the ggthemr yet after ggplot2 version 2.0 came up. Try my fork of ggthemr available at https://github.com/sainathadapa/ggthemr, until @cttobin updates the main repo.

**Comment by jbkunst** [comment]
:+1: This package needs love and someone to keep it updated. Thanks @sainathadapa

@Emaasit, I think it's a good idea show the @sainathadapa version until @cttobin appears because this package is really a nice alternative to ggthemes.

**Comment by sainathadapa** [comment]
I like ggthemr themes and use it fairly regularly in my plots. I am happy to help and fix any bugs if anyone is facing issues in using my fork.

**Comment by bhaskarvk** [comment]
+1 on adding @sainathadapa's fork.

**Comment by sainathadapa** [comment]
FYI the main ggthemr repo (https://github.com/cttobin/ggthemr) is now updated to work with ggplot version > 2

**Comment by sainathadapa** [comment]
Entry for ggthemr is up. This issue can be closed. @Emaasit
