### ISSUE TITLE
new ggplots exts

### ISSUE THREAD

**Issue by omarbenites** [ggplot2-exts/ggplot2-exts.github.io#3]
Hello Daniel,
These are my ggexts packages to add:
1. gganimate: Create easy animations with ggplot2 
   Github Repo: [https://github.com/dgrtwo/gganimate](url) 
2. sjPlot: ggplot exts for Data Visualization for Statistics in Social Science 
   Github Repo: [https://github.com/sjPlot/devel](url)
   Examples and Documentation [http://strengejacke.de/sjPlot/](url)

**Comment by jemus42** [comment]
I wouldn't call sjPlot a ggplot2 extension package. It's basically a bunch of functions building on top of ggplot2, and while I like an use them regularly, they don't provide any new geoms, scales or whatever in a way the new extensions building on top of ggplot2 2.0 do.

It is, however, extraordinarily useful.

**Comment by Emaasit** [comment]
I agree with @jemus42 , since many actual ggplot2 extensions are being submitted, let's reserve that space for them. Thanks though @omarbenites , I had never heard of "sjPlot" and now am dying to explore it.

**Comment by Emaasit** [comment]
Thanks @omarbenites . I have added gganimate.

**Comment by omarbenites** [comment]
Yep. Probably it's an useful tool for ggplot, but not exactly a ggplot extension. On the other hand (if it is possible), I think would be a good idea create a topic for ggplot wrappers (like sjPLot).
Thanks @Emaasit, it's a really good work
