### ISSUE TITLE
ggpmisc: plotting linear regression equation forced through the origin

### ISSUE THREAD

**Issue by wraseman** [ggplot2-exts/ggplot2-exts.github.io#38]
Hello and thanks for your work on ggpmisc!

I ran into a small issue when trying to plot a linear regression equation forced through the origin. 

I have a dataframe that looks like this...
![image](https://user-images.githubusercontent.com/14048152/54157587-3c18cd00-440e-11e9-80b3-5f9eb1c29b1e.png)

I'm trying to create a scatterplot of Total Hardness vs. Calcium Hardness and the linear regression equation on the plot with R^2. Using stat_poly_eq() I am very close but can't get the equation quite right. 

![image](https://user-images.githubusercontent.com/14048152/54157843-c103e680-440e-11e9-8039-7b881b0c31f0.png)

The equation reads "yhat = 0.267" (see above) when it should read "yhat = 0.267x". It works when I don't force the equation through the origin but not when I do. Don't know if this is a bug or my lack of familiarity with the syntax. 

Thanks!

**Comment by Emaasit** [comment]
@wraseman The best place to file this issue is at the respective package website: https://docs.r4photobiology.info/ggpmisc/. The author of the package is @aphalo  Pedro J. Aphalo (pedro.aphalo@helsinki.fi).
