### ISSUE TITLE
Old domain now points to a Russian pornographic site!

### ISSUE THREAD

**Issue by aphalo** [ggplot2-exts/ggplot2-exts.github.io#39]
https://exts.ggplot2.tidyverse.org/
Consequently, as my package documentation still points to the old URL, it forces me to submit a new version of my package to CRAN, only to update the URL. Others may be affected as well as web pages and blog posts.

The problem with my package documentation was reported to me by Ethan Young and I confirmed that this is happening.

**Comment by yutannihilation** [comment]
Thanks for reporting this and I'm sorry for the hassle. We know this, but there's not much we can do. Once the domain is lost, it's very hard to get it back. This is what the Internet is...

c.f. https://github.com/ggplot2-exts/gallery/issues/87
